### ISSUE TITLE
Get jar working again

### ISSUE THREAD

**Issue by Kody-Belisle** [Kody-Belisle/Diagnostic-Report-Generator#57]
Look into deployment through ant file or look into Gradle

Ties to #59

**Comment by HJohnson748** [comment]
Links from the Apache Derby site related to deployment
https://db.apache.org/derby/docs/10.0/manuals/develop/develop32.html#HDRSII-DEPLOY-18639

https://db.apache.org/derby/docs/10.0/manuals/develop/develop12.html#HDRSII-DEVELOP-13018
